---
title: "Read EML metadata"
author: "Corinna Gries"
date: "2021-10-19"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Read EML metadata}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



The EDIutils package provides R wrappers to the EDI data repository REST API functions. 

This vignette demonstrates how to query the EDI repository for the newest EML metadata for an LTER site using the scope or using a keyword. The EML files may then be used to analyze their content or update metadata. 

#### Set up the R environment

```{r eval=FALSE}
# This vignette uses a development version of EDIutils on the "cran" branch
remotes::install_github("EDIorg/EDIutils", ref = "cran")
```

```r
library(EDIutils)
library(xml2)
```

Several EDI API functions return XML, `xml2` is a convenient package to extract desired information and to save returned EML files locally.

## Search for datasets by using the LTER site scope

NTL will be used as example throughout, change to different scope.

#### Query EDI for all data package IDs in a certain scope.


```r
scope <- "knb-lter-ntl"
identifiers <- list_data_package_identifiers(scope = scope, env = "production")
```

#### Query EDI for the latest revision of each data package

Build the correct metadata ID and save in a vector in the format of, e.g. knb-lter-ntl.1.52


```r
package_ids <- c()
for (i in 1:length(identifiers)) {
  revision <- list_data_package_revisions(scope = scope,
                                          identifier = identifiers[i],
                                          filter = "newest",
                                          env = "production")
  package_ids[i] <- paste(scope,identifiers[i],revision, sep = ".")
}
```

## Search for datasets by using a keyword

In this example the search is for the keyword "Trout Lake Station".

#### Query EDI for data packages based on a keyword

Determine how many datasets were found and set the return limits accordingly in the query parameters. Then search returns the latest package IDs as an XML file.


```r
query <- 'q=%22Trout+Lake+Station%22&fl=packageid'
package_ids_xml <- search_data_packages(query = query)
numFound <- xml_attr(package_ids_xml, "numFound")
query <- paste(query, "&rows=", numFound, sep = "")
package_ids_xml <-search_data_packages(query = query)
```

#### Parse the returned XML to get package IDs


```r
package_ids <- xml_text(xml_find_all(package_ids_xml, "//packageid"))
```


## Read the EML file for each of the data package IDs discovered. 

It is recommended to save them locally for further processing as these operations can be taxing on the repository.The example code below only keeps one EML file in the variable and does not create one giant XML document with all EML files returned. Each EML file is written to the local working directory with its package ID as file name.


```r
for (j in 1:length(package_ids)) {
  eml_file <- read_metadata(packageId = package_ids[j])
  
  #write each file to local folder:
  #write_xml(eml_file, file = paste(package_ids[j], "xml", sep = "."))
}
```


