#' Create a data package for testing upload, evaluation, or delete operations
#'
#' @param path (character) Path to which the test files will be written
#'
#' @return A directory containing a data object and an EML file describing the data object
#' 
#' @note This function only gets you half way there. After written to \code{path} you'll have: (1) Host data.txt at a web accessible location for download by the EDI repository, (2) Get the URL to data.txt and add it to the "eml.xml" file at the xpath ".//otherEntity/physical/distribution/online/url".
#' 
#' Once configured, "eml.xml" is the basis for all future tests, because it links to the now web accessible "data.txt". Use \code{create_test_eml()) to create new EML documents for testing.
#' 
#' @noRd
#' 
#' @examples 
#' \dontrun{
#' # Source this module to access functions
#' source(system.file("extdata", "/pkg_test/pkg_test.R", package = "EDIutils"))
#' 
#' # Create directory of test files
#' create_test_package(path = "/Users/me/Documents")
#' }
#' 
create_test_package <- function(path) {
  f <- system.file("extdata", "pkg_test", package = "EDIutils")
  file.copy(from = f, to = path, recursive = TRUE)
  eml <- xml2::read_xml(paste0(path, "/pkg_test/eml.xml"))
  md5 <- tools::md5sum(paste0(path, "/pkg_test/data.txt"))
  n <- xml2::xml_find_all(eml, ".//authentication")
  xml2::xml_text(n) <- md5
  file.remove(paste0(path, "/pkg_test/eml.xml"))
  xml2::write_xml(eml, paste0(path, "/pkg_test/eml.xml"))
}








#' Create an EML file for testing
#'
#' @param path (character) Path to directory containing the test EML file "eml.xml", generated by \code{create_test_package()}.
#' @param packageId (character) Package identifier, of the form "scope.identifier.revision", for the new EML file.
#' @param dn (character) Distinguished name of user. Use \code{construct_dn()} to create input to this argument.
#' 
#' @return (.xml) An EML file
#' 
#' @details Copies "eml.xml" at \code{path} to \code{paste0(path, "/", packageId, ".xml)}
#' 
#' @noRd
#' 
#' @examples
#' \dontrun{
#' # Source this module to access functions
#' source(system.file("extdata", "/pkg_test/pkg_test.R", package = "EDIutils"))
#' 
#' # Create new EML file for a test
#' dn <- construct_dn("me")
#' create_test_eml("/Users/me/Documents/pkg_test", "edi.1.1", dn)
#' }
#' 
create_test_eml <- function(path, packageId, dn) {
  eml <- xml2::read_xml(paste0(path, "/eml.xml"))
  xml2::xml_attr(eml, "packageId") <- packageId
  principal <- xml2::xml_find_first(eml, ".//principal")
  xml2::xml_text(principal) <- dn
  xml2::write_xml(eml, paste0(path, "/", packageId, ".xml"))
}