#' Create reservation
#'
#' @description
#'     Create Reservation operation, creates a new reservation in PASTA for the 
#'     specified user on the next reservable identifier for the specified 
#'     scope. The integer value of the reserved identifier (as assigned by 
#'     PASTA) is returned in the web service response body. User authentication 
#'     is required.
#'
#' @usage create_reservation(scope, environment, user.id, user.pass, affiliation)
#'
#' @param scope
#'     (character) Scope of identifier to be reserved (e.g. edi, knb-lter-ntl).
#' @param environment
#'     (character) Data repository environment in which to reserve the
#'     identifier. Can be: 'development', 'staging', 'production'.
#' @param user.id
#'     (character) Identification of user reserving the identifier.
#' @param user.pass
#'     (character) Password corresponding with the user.id argument supplied
#'     above.
#' @param affiliation
#'     (character) Affiliation corresponding with the user.id argument supplied
#'     above. Can be: 'LTER' or 'EDI'.
#'
#' @return
#'     (character) Package identifier.
#'
#' @export
#'

create_reservation <- function(scope, environment, user.id, user.pass, affiliation){

  validate_arguments(x = as.list(environment()))

  poll_pkg_reserve_id(
    httr::POST(
      url = paste0(url_env(environment), 
                   '.lternet.edu/package/reservations/eml/', scope),
      config = httr::authenticate(auth_key(user.id, affiliation), user.pass)
    )
  )

}





#' Polling loop for reserving package IDs
#'
#' @description
#'     Polling loop for reserving package IDs.
#'
#' @usage poll_pkg_reserve_id(r)
#'
#' @param r
#'     (response) Response generated by `httr::POST`.
#'
#' @return
#'     (character) Package identifier.
#'
#' @export
#'

poll_pkg_reserve_id <- function(r){
  while (TRUE){
    Sys.sleep(2)
    if (r$status_code == '201'){
      reserved_pkg_id <- httr::content(r, as = 'text', encoding = 'UTF-8')
      return(reserved_pkg_id)
      break
    } else if (r$status_code == '401'){
      stop('You are not authorized to create subscriptions.')
      break
    } else if (r$status_code == '400'){
      stop('Request entity contains an error.')
      break
    }
  }
}

